### ISSUE TITLE
com.jtform9.input-observable?

### ISSUE THREAD

**Issue by favoyang** [jtfrom9/Arex#1]
Hi @jtfrom9,

Favo from OpenUPM. Thanks for sharing the package. Seems missing a dependency "com.jtform9.input-observable", I can not find it from the Internet.

Refs: https://openupm.com/packages/com.jtfrom9.arex/?subPage=deps

**Comment by jtfrom9** [comment]
@favoyang
Sorry, this was my fault. I had already fixed it and force push as 0.0.3. so I thought it would be re-build eventually.

By the way, what kicks the pipeline ? Is it something that happens periodically, rather than being hooked by tag updates from github or something like that?

**Comment by favoyang** [comment]
> Sorry, this was my fault. I had already fixed it and force push as 0.0.3. so I thought it would be re-build eventually.

It's intended. See https://openupm.com/docs/modifying-upm-package.html#modifying-or-deleting-a-published-version

> If you deleted or replaced published Git tags on your GitHub repository without notifying us, the changes will not affect content already published on the OpenUPM.

> By the way, what kicks the pipeline? Is it something that happens periodically, rather than being hooked by tag updates from github or something like that?

> By the way, what kicks the pipeline ? Is it something that happens periodically, rather than being hooked by tag updates from github or something like that?

Periodically. So far every 5 minutes, maybe improved when we get more resources/funding. You can not get the GitHub update event (tag creation) unless you install a GitHub app. We may provide an additional way to ping our server. Still, you have to add something to the CI script.

**Comment by favoyang** [comment]
So, please bump the version to fix a published issue.

**Comment by jtfrom9** [comment]
ok, I understand.

**Comment by jtfrom9** [comment]
@favoyang  thank you for your support.
